### ISSUE TITLE
Implement the fmt.Stringer interface for the DeletionReason type

### ISSUE THREAD

**Issue by sammy-hughes** [maypok86/otter#100]
# Clarification and motivation

Inspection of deletion reasons depends on the developer's familiarity with the constant values for DeletionReason. This experience may be improved by adding a `String() string` method to the otter.DeletionReason type, which reports the name of that type. This allows logging DeletionReason values using the format pattern `%v`, to use the result of the String() method instead of the literal value of the DeletionReason.

Because otter.DeletionReason is a direct alias of core.DeletionReason, this method must be added to the core.DeletionReason type. 

# Acceptance criteria

1. Add a `String() string` method to the DeletionReason type.
2. Return values from that function which correspond to the known values for the DeletionReason type.

**Comment by maypok86** [comment]
Hi, it sounds good, yes.
