### ISSUE TITLE
[BUG] undefined: deque.New

### ISSUE THREAD

**Issue by luzj** [maypok86/otter#112]
https://github.com/gammazero/deque  is update to 1.0,  new version undefined: deque.New

**Comment by maypok86** [comment]
Oh, it seems that `deque` deleted the New method for some reason and did not release v2. How annoying...

**Comment by maypok86** [comment]
pull request: https://github.com/gammazero/deque/pull/33

**Comment by maypok86** [comment]
I have published a new [release](https://github.com/maypok86/otter/releases/tag/v1.2.4) that should fix this bug.
