### ISSUE TITLE
support json unmarshal?

### ISSUE THREAD

**Issue by Nyx2022** [maypok86/otter#28]
# Clarification and motivation

i wanna unmarshal []byte from file to a *otter.Cache[string, any],but i get nothing in *otter.Cache[string, any]

# Acceptance criteria

support json unmarshal or how can i unmarshal correctly

**Comment by maypok86** [comment]
Hi, I have given it a lot of thought and most likely otter will not have any at all. I would like otter to solve the in-memory caching problem and do it very well. No more, no less, so as not to bloat the API with a huge number of methods. So saving the entire cache to a file and building a cache from a file is not part of that.

Try [theine](https://github.com/Yiling-J/theine-go) as a solution to your problems, it seems like it was just conceived to solve similar problems to yours.
