### ISSUE TITLE
Request Get Expiration With Get

### ISSUE THREAD

**Issue by MrSametBurgazoglu** [maypok86/otter#56]
# Clarification and motivation
I have a script that updating some variables and users get them from cache. But I want to get expiration for showing them last update time.

# Acceptance criteria
Get expiration time with get function or new function with expiration time

**Comment by maypok86** [comment]
Hi, thanks for the issue. 

I was going to rework the API a bit later. For now you can use something like this.

```go
package main

import (
	"time"

	"github.com/maypok86/otter"
)

type WithTime[V any] struct {
	Value     V
	UpdatedAt time.Time // or in seconds
}

type Cache[K comparable, V any] struct {
	cache otter.Cache[K, WithTime[V]]
}

func NewCache[K comparable, V any](capacity int) (*Cache[K, V], error) {
	b, err := otter.NewBuilder[K, WithTime[V]](capacity)
	if err != nil {
		return nil, err
	}

	c, err := b.WithTTL(time.Hour).Build()
	if err != nil {
		return nil, err
	}

	return &Cache[K, V]{
		cache: c,
	}, nil
}

func (c *Cache[K, V]) Get(key K) (WithTime[V], bool) {
	return c.cache.Get(key)
}

func (c *Cache[K, V]) Set(key K, value V) bool {
	updatedAt := time.Now()
	return c.cache.Set(key, WithTime[V]{
		Value:     value,
		UpdatedAt: updatedAt,
	})
}
```

**Comment by maypok86** [comment]
@MrSametBurgazoglu @proost

What do you think of this solution to this problem? It's a bit non-standard for Go, but allows otter to hide a lot of future features.

```go
c, err := MustBuilder[int, int](256).
	WithTTL(time.Hour).
	Build()

...

// if you want to get the value without updating the eviction policy
value, ok := c.Advanced().GetQuietly(1)

...

// if you want to get an entry
entry, ok := c.Advanced().GetEntry(1)

...

// if you want to get an entry without updating the eviction policy
entry, ok := c.Advanced().GetEntryQuietly(1)

...

key := entry.Key()
value := entry.Value()
cost := entry.Cost()
expiration := entry.Expiration()
ttl := entry.TTL()
hasExpired := entry.HasExpired()

```

**Comment by proost** [comment]
@maypok86 
First, I want this feature because i plan to apply [PER](https://cseweb.ucsd.edu/~avattani/papers/cache_stampede.pdf)

your proposed API can hide underneath a lot of features. what do you expect to user if user get `cost`, `ttl`? 

`GetEntryQuietly` is good to mitigate cache miss storm. what is meaning of parameter?

 And I think `Advanced()` is not intuitive name for accessing additional cache functionality. how about `Details()` or `WithMetadata()`?

**Comment by maypok86** [comment]
> your proposed API can hide underneath a lot of features. what do you expect to user if user get cost, ttl?

I assumed something like this
```go
key := 1

...

func (c *Cache[K, V]) GetCost(key K) (uint32, error) {
    entry, ok := c.Advanced().GetEntryQuietly(key)
    if !ok {
        return 0, errors.New("a cache entry was not found")
    }
    return entry.Cost(), nil
}
```

> what is meaning of parameter?

In all cases, 1 is just a key.

> Advanced() is not intuitive name for accessing additional cache functionality.

This is a difficult moment. It is unclear which name is better to give. I was also thinking about something like `Features` or `Details`, but I'm very likely to add more than just functions to get values there, and then `Details` will become strange.

**Comment by proost** [comment]
> This is a difficult moment. It is unclear which name is better to give. I was also thinking about something like Features or Details, but I'm very likely to add more than just functions to get values there, and then Details will become strange.

how about `Extended()`? `Advanced()` is unfamiliar name.

> your proposed API can hide underneath a lot of features. what do you expect to user if user get cost, ttl?
I mean what is use case if user can get `cost` or `ttl`?

**Comment by maypok86** [comment]
> how about Extended()?

Hmm, it looks interesting. But probably just `Extension` will be clearer.

**Comment by maypok86** [comment]
@proost So, I think we've come to an agreement, right?

**Comment by MrSametBurgazoglu** [comment]
@maypok86  I apologize for not being able to answer. Speaking for myself, this is a good solution. But I didn't understand the meaning of updating eviction policy.

**Comment by proost** [comment]
@maypok86 I agree. Thank you for a new feature!
