### ISSUE TITLE
Feature: Adding more rich stats

### ISSUE THREAD

**Issue by proost** [maypok86/otter#57]
# Clarification and motivation

I need stats for 
1. how many set operation is rejected at time
2. cost metrics for adding/updating at time
3.  how many keys are evicted at time

these stats give me a chance to tune cache configuration and to monitor cache operation is fine.

# Acceptance criteria

**Comment by proost** [comment]
@maypok86 
1. I use "rejected" as broader meaning. So both cases are included. but to clarify the metrics, it can divide two different metrics.
2. of course, deletion should not be counted as eviction metrics.

**Comment by maypok86** [comment]
Damn, I realized that I don't understand what your second point means at all. :(. Do you want to count all the cost that was added to the cache? It seems strange and the applicability is not very clear.

**Comment by proost** [comment]
@maypok86 
If there is rejected set operation, then those costs are should be ignored. along with metrics, that how many successful set operations are made can figure out average cost.

**Comment by maypok86** [comment]
@proost
1. Oh, you meant the average cost of entries... Probably, it will not be very pleasant to count the honest average cost of entries in a high concurrent environment, but maybe the additional `evictedCost` metric will suit you? Using it and the `evictedCount`, it will be possible to roughly estimate the average cost of entries in the cache.
2. Most likely, it is not necessary to count the number of successful Set operations, I don't know the useful use of such a metric.

**Comment by proost** [comment]
@maypok86 `evictedCount` is good. if `evictedCount` is supported, i don't need `cost metrics for adding/updating at time`

**Comment by maypok86** [comment]
@proost, please take a look, will this solution suit you?

**Comment by proost** [comment]
@maypok86 Yes. Thank you!

**Comment by maypok86** [comment]
Okay, then I'll finish the job and upload the v1.1.0 release
