### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by woodliu** [maypok86/otter#62]
https://github.com/maypok86/otter/blob/c66ac1f90a4adddca0c108683920fff904cff30a/internal/hashtable/map.go#L148
With this code, there is an error in my IDE, maybe   `atomic.StorePointer(&m.table, unsafe.Pointer(&t))`?

![image](https://github.com/maypok86/otter/assets/9976943/4d2090e2-6a58-4f7c-8b79-3b2755f04699)

**Comment by maypok86** [comment]
Hi, I don't have this on any of the compiler versions (1.18, 1.19, 1.20, 1.21). Try to reset the ide caches or reboot.

**Comment by woodliu** [comment]
> Hi, I don't have this on any of the compiler versions (1.18, 1.19, 1.20, 1.21). Try to reset the ide caches or reboot.

Hi, i ran it in golang Playground, it should work with or without `&`. The problem may caused by my cache...
