### ISSUE TITLE
is this lru cache? can u make it lru without ttl feature?

### ISSUE THREAD

**Issue by kolinfluence** [maypok86/otter#70]
is this lru cache? can u make it lru without ttl feature?

**Comment by maypok86** [comment]
1. No, this is not an LRU cache, otter uses `S3-FIFO` as an eviction policy. But I don't really understand why you need LRU specifically, given that S3-FIFO and W-TinyLFU are simply more efficient on **any** workloads.
2. Otter already has to work without ttl, moreover, in this configuration it consumes memory as if it does not know how to work with ttl (expiration time and expiration policy will not be stored).
```go
capacity := 10000
cache, err := otter.MustBuilder[int, int](capacity).Build()
if err != nil {
	panic(err)
}
key := 2
value := 3
cache.Set(key, value)
v, ok := cache.Get(key)
if !ok {
	panic("not found key")
}
if v != value {
	panic("not valid value")
}
```

**Comment by kolinfluence** [comment]
@maypok86 just learn something new. thx!
