### ISSUE TITLE
can you do a disk backed version of this?

### ISSUE THREAD

**Issue by kolinfluence** [maypok86/otter#71]
is there any possibility for disk backed version? async or otherwise with in memory cache or without

**Comment by maypok86** [comment]
Otter was conceived as an in-memory cache only, so it is unlikely to be added to the original repository.

If you need this functionality, then you can try https://github.com/Yiling-J/theine-go

**Comment by maypok86** [comment]
I think this issue has been resolved. If you need something else, then write.
