### ISSUE TITLE
List of keys in the cache

### ISSUE THREAD

**Issue by graymind75** [maypok86/otter#75]
# Clarification and motivation
Hi, Is there anyway to get array of all keys?
And if no, Do you have any intention to add this feature?

# Acceptance criteria
I need to get list of keys exist in the cache at certain point of my program that i don't have keys.

**Comment by maypok86** [comment]
Hi, this has already been asked about several times and so far I have not changed my mind about it.

Otter won't have methods like `GetAllKeys` for a very long time.

But you can get similar behavior using the `Range` method.

```go
var keys []K
cache.Range(func(key K, value V) bool {
	keys = append(keys, key)
	return true
})
```
