### ISSUE TITLE
[BUG] About S3-FIFO evict 

### ISSUE THREAD

**Issue by woodliu** [maypok86/otter#77]
When the cache [full](https://github.com/maypok86/otter/blob/main/internal/s3fifo/policy.go#L66) , it should evict some nodes.
From the S3-FIFO [paper](https://dl.acm.org/doi/pdf/10.1145/3600006.3613147), when evict node from `small` or `main` queue, it should try to evict the node from the tail, like:
<img width="593" alt="image" src="https://github.com/maypok86/otter/assets/9976943/8d75cfa4-9549-4f8b-a5bf-6952004c4f9c">
But [here](https://github.com/maypok86/otter/blob/main/internal/s3fifo/small.go#L53) , it choose the evicted node from head, is this more reasonable ?

**Comment by woodliu** [comment]
Sorry, my fault , it inset to the tail, and evict from head...

**Comment by maypok86** [comment]
Yes, it is only important to maintain FIFO order there. I put it in the tail and remove it from the head, because it is more familiar and intuitive for me. Also, this option is usually used more often because it has analogies from real life. For example, a queue at a store.
