### ISSUE TITLE
Add the copied map version

### ISSUE THREAD

**Issue by woodliu** [maypok86/otter#78]
https://github.com/maypok86/otter/blob/9d61c676ef185402bac4a291b46ee6b72c83bebf/internal/hashtable/map.go#L5
There are many version for [puzpuzpuz/xsync](https://github.com/puzpuzpuz/xsync), i think it is better to add the source mapof version, in case there are some issues that existed in the source, but fixed in latter [releases](https://github.com/puzpuzpuz/xsync/releases).

**Comment by maypok86** [comment]
Hi, otter uses the latest version of `xsync.MapOf` and I check the relevance and issues there quite often. Otter uses the fork to save memory, and also adds some new methods.

**Comment by woodliu** [comment]
Hi, thank you for replying. I am still learning the otter code,  i have to say, there are a lot of wonderful things to learn!
Especially when i read the code `lossy.Buffer.Add`, to support access concurrently, the way it works is very bold and confident.

**Comment by maypok86** [comment]
In fact, there are quite a lot of data structures in otter that had to be implemented manually (hashtable, lossy buffer, growable queue, linked list, state machine). At the same time, S3-FIFO is used as an eviction policy, not W-TinyLFU. Perhaps if we implement a top-level version of it, then the otter can become practically invulnerable. But the main goal for me in the near future will be the release of v2 and the addition of a loader.

**Comment by woodliu** [comment]
> In fact, there are quite a lot of data structures in otter that had to be implemented manually (hashtable, lossy buffer, growable queue, linked list, state machine). At the same time, S3-FIFO is used as an eviction policy, not W-TinyLFU. Perhaps if we implement a top-level version of it, then the otter can become practically invulnerable. But the main goal for me in the near future will be the release of v2 and the addition of a loader.

Yeah, it is hard to implement a cache without(or just use the minimum) locker, for concurrent access, it needs to be careful with every logic, it takes time to create a unbreakable cache.
Hope all go well for you!
