### ISSUE TITLE
Set to invalid hashmap in concurrent situation

### ISSUE THREAD

**Issue by woodliu** [maypok86/otter#87]
`func (m *Map[K, V]) Delete(key K) node.Node[K, V]` and `func (m *Map[K, V]) Set(n node.Node[K, V]) node.Node[K, V]` can  run concurrently, when `Delete` run into this [line](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L379) and `Set` run into this [loop](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L249), there is chance that `Set` node to an invalid(shrinked) table. 
I think this may acceptable in this situation.

And here is another question, in hash map `set`, there is a judgment `if m.newerTableExists(t)`, does it used to lower the probability `set` to an invalid table? Because when concurrently run multi `set`, there still may create a new table even after this judgment `if m.newerTableExists(t)`
Thanks!

**Comment by maypok86** [comment]
> can run concurrently, when Delete run into this [line](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L379) and Set run into this [loop](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L352), there is chance that Set node to an invalid(shrinked) table.

But this one has already taken a lock on the bucket in Delete and the rest will have to wait for the operation to complete.

> Because when concurrently run multi set, there still may create a new table even after this judgment if m.newerTableExists(t)

To be honest, I didn't really understand how this is possible. There is also a lock on the bucket first. Can you explain in more detail, please?

**Comment by woodliu** [comment]
> But this one has already taken a lock on the bucket in Delete and the rest will have to wait for the operation to complete.

Sorry, i post the wrong code link for "_Delete run into this [line](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L379) and Set run into this [loop](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L249),_", please recheck the code again. Here is an example to show how that will happend:

1. When there is no table resizing, A `set` operation can run this [loop](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L249), it will add or update the node in **t.buckets[1]**
2. At the same time, a `delete`  operation just starts to run [resize](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L379) for  **t.buckets[2]**(they are changing the different bucket and using the different locks),  because there is no other table resizing, it will resize the table later. So there is a chance that `delete` creates a brand new shrinked table for hashmap, and `set` will add or update the node in the old table.

> To be honest, I didn't really understand how this is possible. There is also a lock on the bucket first. Can you explain in more detail, please?

This situation just like above, two `set` operateions changing the different table buckets, they use the different locks, so one `set` can run the loop to add or update the node in a bucket, and another `set` can resize when add or update node in another bucket because there is no table resizing.

**Comment by maypok86** [comment]
> So there is a chance that delete creates a brand new shrinked table for hashmap, and set will add or update the node in the old table.

If these operations are performed at the same time, then the lock for `t.buckets[1]` has already been [taken](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L233), which means that when copying entries from this bucket to a new table, the goroutine will have to [wait](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L450) for the bucket to be unlocked.

> So the second set will create a new table for hashmap, and the first set will change the old table, so i think if m.newerTableExists(t) is a soft limit.

Yeah, this is a more interesting case. The main magic here is done by `resizing` and locking the bucket at the beginning of the `Set` execution.

1. If the `Set` [started](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L337) before `resize`, then `resize` will [wait](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L450) for the execution of `Set` to complete due to locking and copy the final result.
2. If the `resize` [started](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L403) before the `Set`, then when [checking](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L236) the `resizing`, we will delay the execution of the `Set` until the completion of the execution of the `resize`.

**Comment by woodliu** [comment]
> > So there is a chance that delete creates a brand new shrinked table for hashmap, and set will add or update the node in the old table.
> 
> If these operations are performed at the same time, then the lock for `t.buckets[1]` has already been [taken](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L233), which means that when copying entries from this bucket to a new table, the goroutine will have to [wait](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L450) for the bucket to be unlocked.
> 
> > So the second set will create a new table for hashmap, and the first set will change the old table, so i think if m.newerTableExists(t) is a soft limit.
> 
> Yeah, this is a more interesting case. The main magic here is done by `resizing` and locking the bucket at the beginning of the `Set` execution.
> 
> 1. If the `Set` [started](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L337) before `resize`, then `resize` will [wait](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L450) for the execution of `Set` to complete due to locking and copy the final result.
> 2. If the `resize` [started](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L403) before the `Set`, then when [checking](https://github.com/maypok86/otter/blob/main/internal/hashtable/map.go#L236) the `resizing`, we will delay the execution of the `Set` until the completion of the execution of the `resize`.

Wow, i missed the lock in `copyBuckets`👍🏻

**Comment by woodliu** [comment]
Wow, i missed the lock in `copyBuckets`👍🏻. 
So `if m.resizeInProgress()` and  `if m.newerTableExists(t)` are soft limit in `set`, and the bucket lock will make sure the data won't conflict, right?

**Comment by maypok86** [comment]
> So if m.resizeInProgress() and if m.newerTableExists(t) are soft limit in set, right?

What do you mean by "soft limit"?

> how about remove the code below from set, does it make sense?

These checks are necessary for the case when we have already started to perform `resize`. Since we could already copy the desired bucket to a new hash table. Because of this, we may lose the entry.  It seems that we should not allow this to happen :).

**Comment by woodliu** [comment]
> What do you mean by "soft limit"?
`soft limit` means lower the  probability that access  the invalid table. You have already explained this in the below answer.

> These checks are necessary for the case when we have already started to perform resize. Since we could already copy the desired bucket to a new hash table. Because of this, we may lose the entry. It seems that we should not allow this to happen :).
Awesome!

**Comment by maypok86** [comment]
So, I've almost solved my problems, so we're starting to sort out the accumulated issues :). It seems that this issue has been resolved, so I'm closing it.
