### ISSUE TITLE
is there any example of "DeletionListener" func？when i use "DeletionListener", it didn't worked

### ISSUE THREAD

**Issue by amos-lsl** [maypok86/otter#95]
newCache, err := otter.MustBuilder[string, string](10).
CollectStats().
Cost(func(key string, value string) uint32 {
	return 1
}).
DeletionListener(func(key, value string, reason otter.DeletionCause) {
	fmt.Printf("newExpire key[%s] expire, value: %s, reason: %d", key, value, reason) //never print
}).
WithVariableTTL().
Build()
if err != nil {
panic(err)
}

for i := 0; i < 2; i++ {
    key := fmt.Sprintf("key-%d", i)
    value := fmt.Sprintf("value-%d", i)
    newCache.Set(key, value, time.Minute)
    time.Sleep(3 * time.Second)
}

time.Sleep(3 * time.Minute)

**Comment by maypok86** [comment]
Hi, since you added fewer items than the size of the buffer used by the otter, the entries were not added to the eviction policy. You can try changing the example so that the capacity is 70 and the number of iterations is 68.

```go
newCache, err := otter.MustBuilder[string, string](70).
  CollectStats().
  Cost(func(key string, value string) uint32 {
    return 1
  }).
  DeletionListener(func(key, value string, reason otter.DeletionCause) {
    fmt.Printf("newExpire key[%s] expire, value: %s, reason: %d", key, value, reason) //never print
  }).
  WithVariableTTL().
  Build()
if err != nil {
  panic(err)
}

for i := 0; i < 68; i++ {
  key := fmt.Sprintf("key-%d", i)
  value := fmt.Sprintf("value-%d", i)
  newCache.Set(key, value, time.Minute)
  time.Sleep(3 * time.Second)
}

time.Sleep(3 * time.Minute)
```

**Comment by amos-lsl** [comment]
> Hi, since you added fewer items than the size of the buffer used by the otter, the entries were not added to the expiration policy. You can try changing the example so that the capacity is 70 and the number of iterations is 68.
> 
> ```go
> newCache, err := otter.MustBuilder[string, string](70).
>   CollectStats().
>   Cost(func(key string, value string) uint32 {
>     return 1
>   }).
>   DeletionListener(func(key, value string, reason otter.DeletionCause) {
>     fmt.Printf("newExpire key[%s] expire, value: %s, reason: %d", key, value, reason) //never print
>   }).
>   WithVariableTTL().
>   Build()
> if err != nil {
>   panic(err)
> }
> 
> for i := 0; i < 68; i++ {
>   key := fmt.Sprintf("key-%d", i)
>   value := fmt.Sprintf("value-%d", i)
>   newCache.Set(key, value, time.Minute)
>   time.Sleep(3 * time.Second)
> }
> 
> time.Sleep(3 * time.Minute)
> ```

thanks
